[tools]
awscli      = "2.27.4"
aws-copilot = "1.27.0"
awsebcli    = "3.20.10"
aws-sam-cli = "1.137.1"
ctop        = "0.7.7"
eksctl      = "0.202.0"
eza         = "0.21.0"
"ubi:a8m/envsubst" = "1.4.3"
"aqua:awslabs/git-secrets" = "1.3.0"
golang      = "1.24.2"
hadolint    = "2.12.0"
helm        = "3.11.2"
jq          = "1.7.1"
kubectl     = "1.24.0"
kubectx     = "0.9.4"
lazydocker  = "0.24.1"
node        = "22.14.0"
peco        = "0.5.11"
"pipx:cfn-lint" = "1.34.1" # dependency uv
python      = "3.11.7"
"ubi:aws-cloudformation/rain" = "1.22.0"
starship    = "1.22.1"
shellcheck  = "0.9.0"
shfmt       = "3.6.0"
stern       = "1.24.0"
uv          = "0.6.12"
"ubi:neosmart/tac" = "2.0"
terraform   = "1.8.3"
yq          = "4.33.2"

[settings]
node.gpg_verify = false
experimental = true
