[tools]
awscli      = "2.18.5"
aws-copilot = "1.27.0"
awsebcli    = "3.20.10"
aws-sam-cli = "1.125.0"
ctop        = "0.7.7"
deno        = "1.22.0"
eksctl      = "0.202.0"
golang      = "1.20.2"
hadolint    = "2.12.0"
helm        = "3.11.2"
jq          = "1.7.1"
kubectl     = "1.24.0"
kubectx     = "0.9.4"
nodejs      = "18.15.0"
peco        = "0.5.11"
python      = "3.11.7"
shellcheck  = "0.9.0"
shfmt       = "3.6.0"
stern       = "1.24.0"
terraform   = "1.8.3"
yq          = "4.33.2"

[settings]
experimental = true
