[tools]
aws-cli     = "2.27.38"
aws-copilot = "1.27.0"
aws-sam     = "1.140.0"
ctop        = "0.7.7"
eksctl      = "0.210.0"
eza         = "0.21.4"
"ubi:a8m/envsubst" = "1.4.3"
"aqua:awslabs/git-secrets" = "1.3.0"
golang      = "1.24.2"
hadolint    = "2.12.0"
helm        = "3.18.3"
jq          = "1.7.1"
kubectl     = "1.32.6"
kubectx     = "0.9.4"
lazydocker  = "0.24.1"
node        = "22.14.0"
"npm:@google/gemini-cli" = { version = "latest", condition = "{{ os() == 'windows' }}" }
peco        = "0.5.11"
"pipx:cfn-lint" = "1.36.0"
python      = ["3.12.10", "3.11.7"]
"ubi:aws-cloudformation/rain" = "1.22.0"
starship    = "1.22.1"
shellcheck  = "0.9.0"
shfmt       = "3.6.0"
stern       = "1.24.0"
usage       = "2.1.1"
uv          = "0.7.13"
"ubi:neosmart/tac" = "2.0"
terraform   = "1.8.3"
yq          = "4.33.2"

[settings]
node.gpg_verify = false
experimental = true
