[tools]
awscli      = "2.21.1"
aws-copilot = "1.27.0"
awsebcli    = "3.20.10"
aws-sam-cli = "1.125.0"
ctop        = "0.7.7"
eksctl      = "0.202.0"
golang      = "1.20.2"
hadolint    = "2.12.0"
helm        = "3.11.2"
jq          = "1.7.1"
kubectl     = "1.24.0"
kubectx     = "0.9.4"
nodejs      = "18.15.0"
peco        = "0.5.11"
uv          = "0.6.12"
python      = "3.11.7"
shellcheck  = "0.9.0"
shfmt       = "3.6.0"
stern       = "1.24.0"
terraform   = "1.8.3"
yq          = "4.33.2"

# npm packages
"npm:textlint" = "14.6.0"
"npm:textlint-rule-common-misspellings" = "1.0.1"
"npm:textlint-rule-preset-ja-spacing" = "2.4.3"
"npm:textlint-rule-preset-ja-technical-writing" = "12.0.2"
"npm:textlint-rule-spellcheck-tech-word" = "5.0.0"
"npm:textlint-rule-write-good" = "2.0.0"

[settings]
experimental = true
